version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    labels:
      - "maven"
      - "dependencies"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/src"
    # Check for updates once a week
    schedule:
      interval: "monthly"
    labels:
      - "docker"
      - "dependencies"
